### ISSUE TITLE
Links open in the same browser tab

### ISSUE THREAD

**Issue by d0rich** [exactpro/docs-toolkit#6]
**Describe the bug**
Links leading to external resources are opened in the same browser tab. In result, documentation is closed, and we need to do more actions during navigation.

**To Reproduce**
1. Go to https://exactpro.github.io/docs-toolkit/
2. Click on [NodeJS LTS 16+](https://nodejs.org/en/) link
3. See Node.js page opened in the same tab

**Expected behavior**
Node.js page is opened in new browser tab.

**Comment by Hdd87** [comment]
Hi Kolya , so when I go to https://exactpro.github.io/docs-toolkit/#quick-start and click on [NodeJS LTS 16+](https://nodejs.org/en/) link it opens in the same tab

**Comment by d0rich** [comment]
> Hi Kolya , so when I go to https://exactpro.github.io/docs-toolkit/#quick-start and click on [NodeJS LTS 16+](https://nodejs.org/en/) link it opens in the same tab

Correct, it is not expected behavior

**Comment by Hdd87** [comment]
Kolya just to verify , is installing this repo ,  https://github.com/rehypejs/rehype-external-links,  all I have do ? or do I have to do something inside nuxt.config.ts ( https://content.nuxtjs.org/api/configuration/#markdown )

**Comment by d0rich** [comment]
@Hdd87, you also should configure this plugin in `content.markdown.rehypePlugins` section in `nuxt.config.ts`
